// import { useState } from "react";
// import { Search, Filter, CheckCircle, AlertTriangle, Clock, Download, FileText, File, FileCode } from "lucide-react";

// interface Props {
//   compact?: boolean;
//   theme?: string;
// }

// export default function AuditScreen({ compact = false, theme = "light" }: Props) {
//   const [filterType, setFilterType] = useState("all");
//   const [searchTerm, setSearchTerm] = useState("");
//   const [showExportMenu, setShowExportMenu] = useState(false);

//   const themeColors = {
//     light: {
//       bg: "bg-white",
//       border: "border-[#E5E7EB]",
//       text: "text-[#111827]",
//       textSecondary: "text-[#6B7280]",
//       textTertiary: "text-[#9CA3AF]",
//       hover: "hover:bg-[#F9FAFB]",
//       bgSecondary: "bg-[#F9FAFB]",
//       bgTertiary: "bg-[#FAFAFA]",
//       eventText: "text-[#111827]",
//       policyDecisionBg: "bg-white",
//       policyDecisionText: "text-[#92400E]",
//     },
//     dark: {
//       bg: "bg-[#1E293B]",
//       border: "border-[#334155]",
//       text: "text-white",
//       textSecondary: "text-[#94A3B8]",
//       textTertiary: "text-[#64748B]",
//       hover: "hover:bg-[#334155]",
//       bgSecondary: "bg-[#0F172A]",
//       bgTertiary: "bg-[#1E293B]",
//       eventText: "text-[#111827]",
//       policyDecisionBg: "bg-[#334155]",
//       policyDecisionText: "text-[#FDB022]",
//     },
//     "high-contrast": {
//       bg: "bg-white",
//       border: "border-black",
//       text: "text-black",
//       textSecondary: "text-[#4B5563]",
//       textTertiary: "text-[#6B7280]",
//       hover: "hover:bg-[#F3F4F6]",
//       bgSecondary: "bg-[#F9FAFB]",
//       bgTertiary: "bg-[#FAFAFA]",
//       eventText: "text-black",
//       policyDecisionBg: "bg-white",
//       policyDecisionText: "text-[#92400E]",
//     },
//   };

//   const colors = themeColors[theme as keyof typeof themeColors] || themeColors.light;

//   const sessionData = {
//     sessionId: "sess_49a2f8c",
//     agent: "Finance Analyst",
//     initiated: "2026-04-21 10:01:03",
//     status: "Pending Approval",
//   };

//   const events = [
//     { time: "10:01:03", event: "Request received", type: "info", icon: "info", detail: 'User request: "Summarize payroll changes..."' },
//     { time: "10:01:04", event: "Plan generated", type: "info", icon: "info", detail: "3 steps identified" },
//     { time: "10:01:05", event: "query_payroll_db", type: "allow", icon: "check", detail: "Policy check passed" },
//     { time: "10:01:06", event: "summarize_results", type: "allow", icon: "check", detail: "Policy check passed" },
//     { time: "10:01:07", event: "send_email", type: "block", icon: "alert", detail: "POL-017 triggered: External data transmission" },
//     { time: "10:01:08", event: "Approval requested", type: "pending", icon: "clock", detail: "Escalated to HR for review" },
//   ];

//   const filteredEvents = events.filter(e => {
//     if (filterType === "allowed") return e.type === "allow";
//     if (filterType === "blocked") return e.type === "block";
//     return true;
//   });

//   const exportToPDF = () => {
//     alert("Exporting to PDF... (Feature demonstration)");
//     // In production, use jsPDF or similar library
//   };

//   const exportToHTML = () => {
//     const html = `
// <!DOCTYPE html>
// <html>
// <head>
//   <title>Audit Report - ${sessionData.sessionId}</title>
//   <style>
//     body { font-family: sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }
//     h1 { color: #111827; }
//     .meta { background: #F9FAFB; padding: 15px; border: 1px solid #E5E7EB; margin: 20px 0; }
//     .event { padding: 15px; border-left: 3px solid #E5E7EB; margin: 10px 0; }
//     .event.allow { border-left-color: #10B981; background: #ECFDF5; }
//     .event.block { border-left-color: #F59E0B; background: #FFFBEB; }
//     .time { font-family: monospace; color: #6B7280; font-size: 12px; }
//     .detail { color: #6B7280; font-size: 14px; margin-top: 5px; }
//   </style>
// </head>
// <body>
//   <h1>PAAC Audit Report</h1>
//   <div class="meta">
//     <p><strong>Session ID:</strong> ${sessionData.sessionId}</p>
//     <p><strong>Agent:</strong> ${sessionData.agent}</p>
//     <p><strong>Initiated:</strong> ${sessionData.initiated}</p>
//     <p><strong>Status:</strong> ${sessionData.status}</p>
//   </div>
//   <h2>Event Timeline</h2>
//   ${filteredEvents.map(e => `
//     <div class="event ${e.type}">
//       <div><strong>${e.event}</strong> <span class="time">${e.time}</span></div>
//       <div class="detail">${e.detail}</div>
//     </div>
//   `).join('')}
//   <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #E5E7EB; color: #6B7280; font-size: 12px;">
//     <p>Generated by PAAC (Policy-Aware Agent Console)</p>
//     <p>© 2026 Truc Tran. Personal project.</p>
//   </footer>
// </body>
// </html>`;

//     const blob = new Blob([html], { type: 'text/html' });
//     const url = URL.createObjectURL(blob);
//     const a = document.createElement('a');
//     a.href = url;
//     a.download = `audit-report-${sessionData.sessionId}.html`;
//     a.click();
//     URL.revokeObjectURL(url);
//   };

//   const exportToMarkdown = () => {
//     const markdown = `# PAAC Audit Report

// ## Session Information
// - **Session ID:** ${sessionData.sessionId}
// - **Agent:** ${sessionData.agent}
// - **Initiated:** ${sessionData.initiated}
// - **Status:** ${sessionData.status}

// ## Event Timeline

// ${filteredEvents.map(e => `### ${e.event}
// **Time:** ${e.time}
// **Details:** ${e.detail}
// **Type:** ${e.type.toUpperCase()}

// ---
// `).join('\n')}

// ---
// *Generated by PAAC (Policy-Aware Agent Console)*
// *© 2026 Truc Tran. Personal project.*
// `;

//     const blob = new Blob([markdown], { type: 'text/markdown' });
//     const url = URL.createObjectURL(blob);
//     const a = document.createElement('a');
//     a.href = url;
//     a.download = `audit-report-${sessionData.sessionId}.md`;
//     a.click();
//     URL.revokeObjectURL(url);
//   };

//   return (
//     <div className={`h-full flex flex-col ${compact ? "text-xs" : "text-sm"}`}>
//       {/* Header */}
//       <div className={`p-3 ${colors.bg} border-b ${colors.border} flex-shrink-0`}>
//         <div className="flex gap-2 mb-3 flex-wrap">
//           <div className="flex-1 min-w-[200px] relative">
//             <Search className={`absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 ${colors.textTertiary}`} />
//             <input
//               type="text"
//               value={searchTerm}
//               onChange={(e) => setSearchTerm(e.target.value)}
//               placeholder="Search session ID..."
//               className={`w-full pl-9 pr-3 py-2 border ${colors.border} ${colors.bgTertiary} ${colors.text} text-sm placeholder:${colors.textTertiary} focus:outline-none focus:border-[#111827]`}
//               aria-label="Search session ID"
//             />
//           </div>
//           <select
//             value={filterType}
//             onChange={(e) => setFilterType(e.target.value)}
//             className={`px-3 py-2 border ${colors.border} ${colors.bgTertiary} ${colors.text} text-sm focus:outline-none focus:border-[#111827]`}
//             aria-label="Filter events"
//           >
//             <option value="all">All Events</option>
//             <option value="allowed">Allowed Only</option>
//             <option value="blocked">Blocked Only</option>
//           </select>

//           {/* Export Button */}
//           <div className="relative">
//             <button
//               onClick={() => setShowExportMenu(!showExportMenu)}
//               className="px-3 py-2 bg-[#111827] text-white text-sm font-medium hover:bg-[#1F2937] transition-colors flex items-center gap-2 whitespace-nowrap"
//               aria-label="Export audit report"
//               aria-expanded={showExportMenu}
//             >
//               <Download className="w-4 h-4" />
//               <span className="hidden sm:inline">Export</span>
//             </button>

//             {showExportMenu && (
//               <div className={`absolute right-0 top-full mt-1 ${colors.bg} border ${colors.border} shadow-lg z-10 min-w-[140px]`}>
//                 <button
//                   onClick={() => { exportToPDF(); setShowExportMenu(false); }}
//                   className={`w-full px-3 py-2 text-left text-sm ${colors.hover} ${colors.text} transition-colors flex items-center gap-2`}
//                 >
//                   <File className="w-4 h-4" />
//                   PDF
//                 </button>
//                 <button
//                   onClick={() => { exportToHTML(); setShowExportMenu(false); }}
//                   className={`w-full px-3 py-2 text-left text-sm ${colors.hover} ${colors.text} transition-colors flex items-center gap-2`}
//                 >
//                   <FileText className="w-4 h-4" />
//                   HTML
//                 </button>
//                 <button
//                   onClick={() => { exportToMarkdown(); setShowExportMenu(false); }}
//                   className={`w-full px-3 py-2 text-left text-sm ${colors.hover} ${colors.text} transition-colors flex items-center gap-2`}
//                 >
//                   <FileCode className="w-4 h-4" />
//                   Markdown
//                 </button>
//               </div>
//             )}
//           </div>
//         </div>

//         <div className="flex items-center gap-4 text-xs flex-wrap">
//           <div className="flex items-center gap-2">
//             <span className={colors.textSecondary}>Session:</span>
//             <span className={`font-mono font-semibold ${colors.text} truncate`}>{sessionData.sessionId}</span>
//           </div>
//           <div className={`w-px h-4 ${colors.border}`}></div>
//           <div className="flex items-center gap-2">
//             <span className={colors.textSecondary}>Agent:</span>
//             <span className={`font-semibold ${colors.text} truncate`}>{sessionData.agent}</span>
//           </div>
//           <div className={`w-px h-4 ${colors.border}`}></div>
//           <div className="flex items-center gap-2">
//             <span className={colors.textSecondary}>Status:</span>
//             <span className="px-2 py-0.5 bg-[#FEF3C7] text-[#92400E] font-semibold whitespace-nowrap">{sessionData.status}</span>
//           </div>
//         </div>
//       </div>

//       {/* Events */}
//       <div className="flex-1 overflow-auto p-3">
//         <div className="space-y-2" role="list" aria-label="Audit events">
//           {filteredEvents.map((event, idx) => {
//             const isBlocked = event.type === "block";
//             const isAllowed = event.type === "allow";

//             return (
//               <div
//                 key={idx}
//                 className={`flex gap-3 p-3 border ${
//                   isBlocked ? "border-[#F59E0B] bg-[#FFFBEB]" :
//                   isAllowed ? "border-[#10B981] bg-[#ECFDF5]" :
//                   `${colors.border} ${colors.bg}`
//                 }`}
//                 role="listitem"
//               >
//                 <div className="flex flex-col items-center flex-shrink-0">
//                   <div className={`w-6 h-6 flex items-center justify-center border ${
//                     isBlocked ? "border-[#F59E0B] bg-[#FEF3C7]" :
//                     isAllowed ? "border-[#10B981] bg-[#D1FAE5]" :
//                     `${colors.border} ${colors.bgSecondary}`
//                   }`} aria-hidden="true">
//                     {event.icon === "check" && <CheckCircle className="w-4 h-4 text-[#10B981]" />}
//                     {event.icon === "alert" && <AlertTriangle className="w-4 h-4 text-[#F59E0B]" />}
//                     {event.icon === "clock" && <Clock className="w-4 h-4 text-[#6B7280]" />}
//                     {event.icon === "info" && <div className="w-1.5 h-1.5 rounded-full bg-[#6B7280]"></div>}
//                   </div>
//                   {idx < filteredEvents.length - 1 && (
//                     <div className={`w-px flex-1 ${colors.border} mt-2`} aria-hidden="true"></div>
//                   )}
//                 </div>

//                 <div className="flex-1 min-w-0">
//                   <div className="flex items-center justify-between mb-1 gap-2">
//                     <span className={`text-sm font-semibold ${isBlocked || isAllowed ? colors.eventText : colors.text} truncate`} title={event.event}>{event.event}</span>
//                     <span className={`text-xs font-mono ${colors.textTertiary} whitespace-nowrap`}>{event.time}</span>
//                   </div>
//                   {event.detail && (
//                     <span className={`text-xs ${colors.textSecondary} block truncate`} title={event.detail}>{event.detail}</span>
//                   )}
//                   {isBlocked && (
//                     <div className={`mt-2 p-2 ${colors.policyDecisionBg} border border-[#F59E0B]`}>
//                       <span className={`text-xs font-semibold ${colors.policyDecisionText}`}>Policy Decision: </span>
//                       <span className={`text-xs ${colors.text}`}>Action requires approval before execution</span>
//                     </div>
//                   )}
//                 </div>
//               </div>
//             );
//           })}
//         </div>
//       </div>

//       {/* Footer */}
//       <div className={`p-3 ${colors.bgSecondary} border-t ${colors.border} flex-shrink-0`}>
//         <div className={`flex items-center gap-2 text-xs ${colors.textSecondary}`}>
//           <div className={`w-4 h-4 border ${colors.border} ${colors.bg} flex items-center justify-center`} aria-hidden="true">
//             <div className={`w-1.5 h-1.5 ${colors.textSecondary === "text-[#6B7280]" ? "bg-[#6B7280]" : colors.textSecondary === "text-[#94A3B8]" ? "bg-[#94A3B8]" : "bg-[#4B5563]"}`}></div>
//           </div>
//           <span>Showing {filteredEvents.length} of {events.length} events</span>
//         </div>
//       </div>
//     </div>
//   );
// }
import { useEffect, useMemo, useState } from "react";
import {
  Search,
  Download,
  CheckCircle2,
  AlertTriangle,
  Clock3,
  ShieldAlert,
} from "lucide-react";
import { api } from "@/lib/api";
import type { DecisionRecord, ThemeMode } from "@/lib/types";

interface Props {
  compact?: boolean;
  theme?: ThemeMode;
  refreshKey?: number;
}

function getThemeColors(theme?: ThemeMode) {
  const isDark = theme === "dark";
  const isHighContrast = theme === "high-contrast";

  if (isHighContrast) {
    return {
      pageBg: "bg-white",
      bg: "bg-white",
      bgSecondary: "bg-[#F3F4F6]",
      bgTertiary: "bg-[#E5E7EB]",
      border: "border-black",
      text: "text-black",
      textSecondary: "text-[#374151]",
      textTertiary: "text-[#6B7280]",
      hover: "hover:bg-[#F3F4F6]",
    };
  }

  return {
    pageBg: isDark ? "bg-[#0F172A]" : "bg-[#FAFAFA]",
    bg: isDark ? "bg-[#1E293B]" : "bg-white",
    bgSecondary: isDark ? "bg-[#0F172A]" : "bg-[#F9FAFB]",
    bgTertiary: isDark ? "bg-[#334155]" : "bg-[#F3F4F6]",
    border: isDark ? "border-[#334155]" : "border-[#E5E7EB]",
    text: isDark ? "text-white" : "text-[#111827]",
    textSecondary: isDark ? "text-[#94A3B8]" : "text-[#6B7280]",
    textTertiary: isDark ? "text-[#64748B]" : "text-[#9CA3AF]",
    hover: isDark ? "hover:bg-[#334155]" : "hover:bg-[#F9FAFB]",
  };
}

export default function AuditScreen({ compact = false, theme, refreshKey = 0 }: Props) {
  const colors = getThemeColors(theme);
  const [events, setEvents] = useState<DecisionRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [searchTerm, setSearchTerm] = useState("");
  const [filterType, setFilterType] = useState<"all" | "allowed" | "blocked">("all");

  useEffect(() => {
    let cancelled = false;

    async function loadDecisions() {
      try {
        setLoading(true);
        const data = await api.getDecisions();
        if (!cancelled) {
          setEvents(data);
          setError(null);
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : "Failed to load audit data");
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    }

    loadDecisions();
    return () => {
      cancelled = true;
    };
  }, [refreshKey]);

  const filteredEvents = useMemo(() => {
    return events.filter((e) => {
      const matchesFilter =
        filterType === "all" ||
        (filterType === "allowed" && e.decision === "allow") ||
        (filterType === "blocked" && e.decision !== "allow");

      const query = searchTerm.trim().toLowerCase();
      const matchesSearch =
        !query ||
        e.trace_id.toLowerCase().includes(query) ||
        e.agent_id.toLowerCase().includes(query) ||
        e.tool.toLowerCase().includes(query) ||
        e.reason.toLowerCase().includes(query);

      return matchesFilter && matchesSearch;
    });
  }, [events, filterType, searchTerm]);

  const latest = events[0];

  function exportAuditJson() {
    const blob = new Blob([JSON.stringify(filteredEvents, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "paac-audit-log.json";
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className={`h-full flex flex-col ${compact ? "text-xs" : "text-sm"} ${colors.pageBg}`}>
      <div className={`p-3 ${colors.bg} border-b ${colors.border} flex-shrink-0`}>
        <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
          <div>
            <div className={`text-xs font-semibold uppercase tracking-[0.16em] ${colors.textSecondary}`}>
              TrustLedger
            </div>
            <h2 className={`text-sm font-semibold mt-1 ${colors.text}`}>Audit Trail</h2>
            <p className={`text-xs mt-1 ${colors.textSecondary}`}>
              Decision provenance for runtime evaluations, matched policies, and risk signals.
            </p>
          </div>

          <div className="flex flex-wrap gap-2">
            <div className={`relative`}>
              <Search className={`absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 ${colors.textTertiary}`} />
              <input
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                placeholder="Search trace, agent, tool..."
                className={`pl-9 pr-3 py-2 border ${colors.border} ${colors.bgSecondary} ${colors.text} text-xs min-w-[240px]`}
              />
            </div>

            <select
              value={filterType}
              onChange={(e) => setFilterType(e.target.value as "all" | "allowed" | "blocked")}
              className={`px-3 py-2 border ${colors.border} ${colors.bgSecondary} ${colors.text} text-xs`}
            >
              <option value="all">All decisions</option>
              <option value="allowed">Allowed only</option>
              <option value="blocked">Blocked / approval</option>
            </select>

            <button
              type="button"
              onClick={exportAuditJson}
              className="px-3 py-2 bg-[#111827] text-white text-xs font-medium hover:bg-[#1F2937] flex items-center gap-2"
            >
              <Download className="w-4 h-4" />
              Export
            </button>
          </div>
        </div>

        {latest && (
          <div className="flex flex-wrap gap-4 mt-3 text-[10px]">
            <div className="flex items-center gap-2">
              <span className={colors.textSecondary}>Latest trace:</span>
              <span className={`font-mono font-semibold ${colors.text}`}>{latest.trace_id}</span>
            </div>
            <div className="flex items-center gap-2">
              <span className={colors.textSecondary}>Agent:</span>
              <span className={`font-semibold ${colors.text}`}>{latest.agent_id}</span>
            </div>
            <div className="flex items-center gap-2">
              <span className={colors.textSecondary}>Decision:</span>
              <span className={`font-semibold ${colors.text}`}>{latest.decision}</span>
            </div>
          </div>
        )}
      </div>

      <div className="flex-1 overflow-auto p-3">
        {loading && <div className={`text-xs ${colors.textSecondary}`}>Loading audit data...</div>}
        {error && <div className="text-xs text-[#EF4444]">{error}</div>}

        {!loading && !error && (
          <div className="space-y-3">
            {filteredEvents.map((event) => {
              const badge =
                event.decision === "allow"
                  ? "text-[#10B981] bg-[#D1FAE5]"
                  : event.decision === "block"
                  ? "text-[#EF4444] bg-[#FEE2E2]"
                  : "text-[#F59E0B] bg-[#FEF3C7]";

              const Icon =
                event.decision === "allow"
                  ? CheckCircle2
                  : event.decision === "block"
                  ? AlertTriangle
                  : Clock3;

              return (
                <div key={`${event.trace_id}-${event.timestamp}`} className={`border ${colors.border} ${colors.bgSecondary}`}>
                  <div className={`p-3 border-b ${colors.border} flex flex-col gap-2 lg:flex-row lg:items-center lg:justify-between`}>
                    <div>
                      <div className={`text-[10px] uppercase tracking-[0.14em] ${colors.textSecondary}`}>
                        {new Date(event.timestamp).toLocaleString()}
                      </div>
                      <div className={`text-xs font-semibold mt-1 ${colors.text}`}>
                        {event.trace_id} · {event.tool}
                      </div>
                    </div>

                    <div className="flex flex-wrap gap-2 items-center">
                      <span className={`px-2 py-0.5 text-[10px] font-bold ${badge}`}>
                        {event.decision.replace("_", " ").toUpperCase()}
                      </span>
                      {typeof event.latency_ms === "number" && (
                        <span className={`px-2 py-0.5 text-[10px] ${colors.bg} border ${colors.border} ${colors.textSecondary}`}>
                          {event.latency_ms} ms
                        </span>
                      )}
                    </div>
                  </div>

                  <div className="p-3 grid grid-cols-1 xl:grid-cols-[1.5fr_1fr] gap-3">
                    <div>
                      <div className={`flex items-start gap-2 text-xs ${colors.text}`}>
                        <Icon className="w-4 h-4 mt-0.5" />
                        <div>
                          <div className="font-medium">Reason</div>
                          <div className={`mt-1 ${colors.textSecondary}`}>{event.reason}</div>
                        </div>
                      </div>

                      <div className="mt-3 grid grid-cols-1 md:grid-cols-2 gap-3">
                        <div className={`p-3 border ${colors.border} ${colors.bg}`}>
                          <div className={`text-[10px] uppercase tracking-[0.14em] ${colors.textSecondary}`}>
                            Agent
                          </div>
                          <div className={`text-xs font-medium mt-1 ${colors.text}`}>{event.agent_id}</div>
                        </div>

                        <div className={`p-3 border ${colors.border} ${colors.bg}`}>
                          <div className={`text-[10px] uppercase tracking-[0.14em] ${colors.textSecondary}`}>
                            Required Approver
                          </div>
                          <div className={`text-xs font-medium mt-1 ${colors.text}`}>
                            {event.required_approver ?? "—"}
                          </div>
                        </div>
                      </div>
                    </div>

                    <div className="space-y-3">
                      <div className={`p-3 border ${colors.border} ${colors.bg}`}>
                        <div className={`text-[10px] uppercase tracking-[0.14em] ${colors.textSecondary}`}>
                          Matched Policies
                        </div>
                        <div className="mt-2 flex flex-wrap gap-1">
                          {event.matched_policies.length > 0 ? (
                            event.matched_policies.map((p) => (
                              <span
                                key={p}
                                className={`px-2 py-0.5 text-[10px] ${colors.bgTertiary} ${colors.text}`}
                              >
                                {p}
                              </span>
                            ))
                          ) : (
                            <span className={`text-xs ${colors.textSecondary}`}>—</span>
                          )}
                        </div>
                      </div>

                      <div className={`p-3 border ${colors.border} ${colors.bg}`}>
                        <div className={`text-[10px] uppercase tracking-[0.14em] ${colors.textSecondary} flex items-center gap-1`}>
                          <ShieldAlert className="w-3 h-3" />
                          Risk Flags
                        </div>
                        <div className="mt-2 flex flex-wrap gap-1">
                          {event.risk_flags && event.risk_flags.length > 0 ? (
                            event.risk_flags.map((flag) => (
                              <span
                                key={flag}
                                className="px-2 py-0.5 text-[10px] bg-[#FEF3C7] text-[#92400E]"
                              >
                                {flag}
                              </span>
                            ))
                          ) : (
                            <span className={`text-xs ${colors.textSecondary}`}>none</span>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}

            {filteredEvents.length === 0 && (
              <div className={`text-xs ${colors.textSecondary}`}>No audit events match the current filters.</div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}